spring:
  activemq:
    broker-url: tcp://192.168.88.116:61617
    in-memory: true
    user: admin
    password: admin
    pool:
      enabled: false
    packages:
      trusted:
        - com.test.entity
  data:
    mongodb:
      uri: mongodb://localhost:27017/mytest