spring:
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
    packages:
      trusted:
        - com.test.entity
  data:
    mongodb:
      uri: mongodb://localhost:27017/mytest